version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      DURATION_LIMIT: $DURATION_LIMIT
      ASSISTANT_PREFIX: $ASSISTANT_PREFIX
      MONGO_DB_URI: $MONGO_DB_URI
      MUSIC_BOT_NAME: $MUSIC_DB_URI
      SUPPORT_CHANNEL: $SUPPORT_CHANNEL
      SUPPORT_GROUP: $SUPPORT_GROUP
      OWNER_ID: $OWNER_ID
      START_IMG_URL: $START_IMG_URL
      STRING_SESSION1: $STRING_SESSION1
      STRING_SESSION2: $STRING_SESSION2
      STRING_SESSION3: $STRING_SESSION3
      STRING_SESSION4: $STRING_SESSION4
      STRING_SESSION5: $STRING_SESSION5
      LOG_GROUP_ID: $LOG_GROUP_ID
      SUDO_USERS: $SUDO_USERS
      LOG_SESSION: $LOG_SESSION
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH
